// frontend/src/pages/Alerts.jsx
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { getAuthenticationStatus, checkAuth, user } from '../services/authService';
import { getCsrfToken } from '../services/csrfService';
import Navbar from '../components/Navbar';
import '../styles/Alerts.css';

const Alerts = () => {
    const [alerts, setAlerts] = useState([]);
    const [error, setError] = useState('');
    const [success, setSuccess] = useState('');
    const navigate = useNavigate();
    const formId = 'alerts-form';

    useEffect(() => {
        const initAlerts = async () => {
            await checkAuth();
            if (!getAuthenticationStatus()) {
                navigate('/login');
                return;
            }
            fetchAlerts();
        };

        initAlerts();
    }, [navigate]);

    const showAlert = (message, type = 'error') => {
        if (type === 'error') setError(message);
        else setSuccess(message);

        setTimeout(() => {
            setError('');
            setSuccess('');
        }, 5000);
    };

    const checkAlertHasCase = async (alertId) => {
        const formId = 'alerts-form';
        try {
            await getCsrfToken(formId);

            const response = await fetch(`http://localhost:4200/backend/alert/has_case/${alertId}`, {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json',
                    'X-Form-ID': formId
                },
                credentials: 'include'
            });

            if (!response.ok) {
                throw new Error('Failed to check alert case status');
            }

            const data = await response.json();
            return data.has_case;
        } catch (err) {
            console.error('Error checking alert case status:', err);
            return false;
        }
    };

    const fetchAlerts = async () => {
        const formId = 'alerts-form';
        try {
            await getCsrfToken(formId);

            const response = await fetch(`http://localhost:4200/backend/alert/all/${user}`, {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json',
                    'X-Form-ID': formId
                },
                credentials: 'include'
            });

            if (!response.ok) {
                throw new Error('Failed to fetch alerts');
            }

            const alertsData = await response.json();

            // Check has_case status for each alert
            const alertsWithCaseStatus = await Promise.all(alertsData.map(async (alert) => {
                const hasCase = await checkAlertHasCase(alert.id);
                return { ...alert, has_case: hasCase };
            }));

            setAlerts(alertsWithCaseStatus);
        } catch (err) {
            console.error('Error fetching alerts:', err);
            showAlert('Failed to load alerts');
        }
    };

    const acknowledgeAlert = async (alertId) => {
        const formId = 'alerts-form';
        try {
            await getCsrfToken(formId);

            const response = await fetch(`http://localhost:4200/backend/alert/acknowledge/${alertId}`, {
                method: 'PUT',
                headers: {
                    'Content-Type': 'application/json',
                    'X-Form-ID': formId
                },
                credentials: 'include'
            });

            if (response.ok) {
                showAlert('Alert acknowledged successfully', 'success');
                fetchAlerts();
            } else {
                throw new Error('Failed to acknowledge alert');
            }
        } catch (err) {
            showAlert('Failed to acknowledge alert');
        }
    };

    const deleteAlert = async (alertId) => {
        if (!window.confirm('Are you sure you want to delete this alert?')) {
            return;
        }

        try {
            const response = await fetch(`http://localhost:4200/backend/alert/${alertId}`, {
                method: 'DELETE',
                headers: {
                    'Content-Type': 'application/json',
                    'X-Form-ID': formId
                },
                credentials: 'include'
            });

            if (response.ok) {
                showAlert('Alert deleted successfully', 'success');
                fetchAlerts();
            } else {
                throw new Error('Failed to delete alert');
            }
        } catch (err) {
            showAlert('Failed to delete alert');
        }
    };

    const addAlertToCase = (alertId) => {
        sessionStorage.setItem('pendingAlertId', alertId);
        navigate('/list-cases?selectCase=true');
    };

    const filterAlertsBySeverity = async (severity) => {
        if (severity === 'all') {
            fetchAlerts();
            return;
        }

        try {
            const response = await fetch(`http://localhost:4200/backend/alert/all/${user}`, {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json',
                    'X-Form-ID': formId
                },
                credentials: 'include'
            });

            if (!response.ok) {
                throw new Error('Failed to fetch alerts');
            }

            const alertsData = await response.json();
            const filteredAlerts = alertsData.filter(alert => 
                alert.severity.toLowerCase() === severity.toLowerCase()
            );
            setAlerts(filteredAlerts);
        } catch (err) {
            console.error('Error filtering alerts:', err);
        }
    };

    return (
        <div className="container">
            <h1>SIEM Alerts</h1>
            <Navbar />
            
            {error && <div className="alert error">{error}</div>}
            {success && <div className="alert success">{success}</div>}

            <div className="filter-container">
                <label htmlFor="severity-filter">Filter by Severity:</label>
                <select 
                    id="severity-filter"
                    onChange={(e) => filterAlertsBySeverity(e.target.value)}
                >
                    <option value="all">All</option>
                    <option value="low">Low</option>
                    <option value="medium">Medium</option>
                    <option value="high">High</option>
                    <option value="critical">Critical</option>
                </select>
            </div>

            <table>
                <thead>
                    <tr>
                        <th>Message</th>
                        <th>Rule ID</th>
                        <th>Severity</th>
                        <th>Timestamp</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {alerts.map(alert => (
                        <tr key={alert.id}>
                            <td>{alert.message}</td>
                            <td>{alert.rule_id}</td>
                            <td>{alert.severity}</td>
                            <td>{new Date(alert.created_at).toLocaleString()}</td>
                            <td>
                                <button
                                    onClick={() => acknowledgeAlert(alert.id)}
                                    disabled={alert.acknowledged}
                                    className="acknowledge-btn"
                                >
                                    {alert.acknowledged ? 'Acknowledged' : 'Acknowledge'}
                                </button>
                                <button
                                    onClick={() => deleteAlert(alert.id)}
                                    className="delete-btn"
                                >
                                    Delete
                                </button>
                                <button
                                    onClick={() => addAlertToCase(alert.id)}
                                    disabled={alert.has_case}
                                    className="add-case-btn"
                                >
                                    {alert.has_case ? 'Added to Case' : 'Add to Case'}
                                </button>
                            </td>
                        </tr>
                    ))}
                </tbody>
            </table>
        </div>
    );
};

export default Alerts;

// frontend/src/routes/alerts/+page.svelte
<script>
  import { onMount } from 'svelte';
  import { getCsrfToken } from '../../services/csrfService';
  import { isAuthenticated, checkAuth, logout } from '../../services/authService.js';

  let alerts = [];
  let sortField = 'timestamp';
  let sortDirection = 'desc';
  let filterSeverity = 'all';
  let alertMessage = '';
  let alertType = 'error';
  let formId = 'alert-form';

  onMount(async () => {
    await checkAuth();
    if (!$isAuthenticated) {
      window.location.href = '/login';
      return;
    }

    try {
      await getCsrfToken(formId);
    } catch (error) {
        alertMessage = 'Failed to fetch CSRF token';
        alertType = 'error';
    }

    await fetchAlerts();
  });

  async function fetchAlerts() {
    // In a real application, this would be an API call
    // For now, we'll use mock data
    alerts = [
      { id: 1, ruleName: 'Suspicious Login', host: '192.168.1.100', severity: 'High', timestamp: '2023-12-08T10:30:00Z' },
      { id: 2, ruleName: 'Failed SSH Attempts', host: '192.168.1.101', severity: 'Medium', timestamp: '2023-12-08T11:15:00Z' },
      { id: 3, ruleName: 'Unusual Network Traffic', host: '192.168.1.102', severity: 'Low', timestamp: '2023-12-08T12:00:00Z' },
      { id: 4, ruleName: 'Malware Detected', host: '192.168.1.103', severity: 'Critical', timestamp: '2023-12-08T13:45:00Z' },
    ];
  }

  function sortAlerts(field) {
    if (sortField === field) {
      sortDirection = sortDirection === 'asc' ? 'desc' : 'asc';
    } else {
      sortField = field;
      sortDirection = 'asc';
    }

    alerts = alerts.sort((a, b) => {
      if (a[field] < b[field]) return sortDirection === 'asc' ? -1 : 1;
      if (a[field] > b[field]) return sortDirection === 'asc' ? 1 : -1;
      return 0;
    });
  }

  function filterAlerts() {
    if (filterSeverity === 'all') {
      fetchAlerts();
    } else {
      alerts = alerts.filter(alert => alert.severity.toLowerCase() === filterSeverity.toLowerCase());
    }
  }

  async function handleLogout() {
      const result = await logout();
      if (!result.success) {
          console.log(result.message);
          alertType = 'error';
          alertMessage = 'Logout unsucesful';
      } else {
          alertType = 'success';
          alertMessage = 'Logout successful';
          window.location.href = '/login';
      }
  }
</script>

<svelte:head>
  <title>Alerts</title>
  <link rel="stylesheet" href="/css/alerts.css">
</svelte:head>

<main>
  <div class="container">
    <h1>SIEM Alerts</h1>

    <div class="filter-container">
      <label for="severity-filter">Filter by Severity:</label>
      <select id="severity-filter" bind:value={filterSeverity} on:change={filterAlerts}>
        <option value="all">All</option>
        <option value="low">Low</option>
        <option value="medium">Medium</option>
        <option value="high">High</option>
        <option value="critical">Critical</option>
      </select>
    </div>

    <table>
      <thead>
        <tr>
          <th on:click={() => sortAlerts('ruleName')}>Rule Name</th>
          <th on:click={() => sortAlerts('host')}>Host</th>
          <th on:click={() => sortAlerts('severity')}>Severity</th>
          <th on:click={() => sortAlerts('timestamp')}>Timestamp</th>
        </tr>
      </thead>
      <tbody>
        {#each alerts as alert (alert.id)}
          <tr class={alert.severity.toLowerCase()}>
            <td>{alert.ruleName}</td>
            <td>{alert.host}</td>
            <td>{alert.severity}</td>
            <td>{new Date(alert.timestamp).toLocaleString()}</td>
          </tr>
        {/each}
      </tbody>
    </table>

    <nav>
      <a href="/">Back to Dashboard</a>
      <button on:click={handleLogout} id="logout-btn">Logout</button>
    </nav>
  </div>
</main>
