// frontend/src/routes/login/+page.svelte
<script>
  let username = '';
  let password = '';
  let alertMessage = '';
  let alertType = '';

  async function handleSubmit() {
    const loginData = {
    	id: "0",
      name: username,
      password: password,
      role: "no"
    };

    try {
      const response = await fetch('http://localhost:4200/backend/account/login', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(loginData),
        credentials: 'include'
      });

      const contentType = response.headers.get('Content-Type') || '';
      let errorMessage = '';

      if (!response.ok) {
        if (contentType.includes('application/json')) {
          const errorData = await response.json();
          errorMessage = errorData.message || 'Failed to log in.';
        } else {
          const errorText = await response.text();
          errorMessage = `Unexpected response: ${errorText}`;
        }
        throw new Error(errorMessage);
      }

      if (contentType.includes('application/json')) {
        const data = await response.json();
        alertMessage = 'Login successful!';
        alertType = 'success';
      } else {
        alertMessage = 'Login successful, but response is not JSON.';
        alertType = 'success';
      }
    } catch (error) {
      console.error('Error logging in:', error);
      alertMessage = `Error: ${error.message}`;
      alertType = 'error';
    }
  }
</script>

<svelte:head>
  <link rel="stylesheet" href="/css/login.css">
  <title>Login</title>
</svelte:head>

<main>
  <div id="container">
    <h1>Login</h1>
    {#if alertMessage}
      <div class={`alert ${alertType}`}>
        {alertMessage}
      </div>
    {/if}
    <form on:submit|preventDefault={handleSubmit}>
      <div>
        <label for="username">Username:</label>
        <input type="text" id="username" bind:value={username} required>
      </div>
      <div>
        <label for="password">Password:</label>
        <input type="password" id="password" bind:value={password} required>
      </div>
      <button type="submit">Log In</button>
    </form>
    <p>New to our platform? <a href="/register">Register here</a></p>
    <p>Visit <a href="https://svelte.dev/docs/kit" target="_blank">svelte.dev/docs/kit</a> to read the documentation</p>
  </div>
</main>

// frontend/src/pages/Login.jsx
import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import '../styles/LogReg.css';

const Login = () => {
    const [formData, setFormData] = useState({
        username: '',
        password: ''
    });
    const [error, setError] = useState('');
    const [isLoading, setIsLoading] = useState(false);
    const navigate = useNavigate();

    const handleChange = (e) => {
        setFormData({
            ...formData,
            [e.target.name]: e.target.value
        });
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        setError('');
        setIsLoading(true);

        try {
            const response = await fetch('http://localhost:4200/backend/auth/login', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                credentials: 'include',
                body: JSON.stringify(formData)
            });

            const data = await response.json();

            if (!response.ok) {
                throw new Error(data.message || 'Login failed');
            }

            localStorage.setItem('user', JSON.stringify(data.user));
            navigate('/dashboard');
        } catch (err) {
            setError(err.message);
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="auth-container">
            <div className="auth-box">
                <h2>Login</h2>
                {error && <div className="error-message">{error}</div>}
                <form onSubmit={handleSubmit}>
                    <div className="form-group">
                        <label htmlFor="username">Username</label>
                        <input
                            type="text"
                            id="username"
                            name="username"
                            value={formData.username}
                            onChange={handleChange}
                            required
                        />
                    </div>
                    <div className="form-group">
                        <label htmlFor="password">Password</label>
                        <input
                            type="password"
                            id="password"
                            name="password"
                            value={formData.password}
                            onChange={handleChange}
                            required
                        />
                    </div>
                    <button 
                        type="submit" 
                        className="auth-button"
                        disabled={isLoading}
                    >
                        {isLoading ? 'Logging in...' : 'Login'}
                    </button>
                </form>
                <p className="auth-link">
                    Don't have an account? <Link to="/register">Register here</Link>
                </p>
            </div>
        </div>
    );
};

export default Login;
