// frontend/src/routes/settings/+page.svelte
<script>
  let newAccount = { username: '', password: '', role: 'analyst' };
  let newLogSource = { name: '', type: 'syslog', address: '' };
  let newHost = { name: '', ip: '' };

  async function createAccount(event) {
      event.preventDefault();

      const newAccount = {
          id: "0",
          name: document.getElementById('name').value,
          password: document.getElementById('password').value,
          role: document.getElementById('role').value || 'Analyst'
      };

      try {
          const response = await fetch('http://localhost:4200/backend/account/', {
              method: 'POST',
              headers: {
                  'Content-Type': 'application/json',
              },
              body: JSON.stringify(newAccount),
          });

          const contentType = response.headers.get("content-type");
          if (contentType && contentType.includes("application/json")) {
              const data = await response.json();
          } else {
              const text = await response.text();
              throw new Error("Expected JSON but received non-JSON response");
          }
      } catch (error) {
          console.error("Error creating account:", error);
          alert(`Error: ${error.message}`);
      }
  }

  function addLogSource(event) {
    event.preventDefault();
    console.log('Adding new log source:', newLogSource);
    // Implement log source addition logic here
    newLogSource = { name: '', type: 'syslog', address: '' };
  }

  function addHost(event) {
    event.preventDefault();
    console.log('Adding new host:', newHost);
    // Implement host addition logic here
    newHost = { name: '', ip: '' };
  }
</script>

<svelte:head>
  <link rel="stylesheet" href="/css/settings.css">
  <title>Settings</title>
</svelte:head>

<main>
  <div id="container">
    <h1>SIEM Settings</h1>

    <section>
      <h2>Create New Account</h2>
      <form on:submit={createAccount}>
        <div>
          <label for="name">Name:</label>
          <input type="text" id="name" bind:value={newAccount.name} required>
        </div>
        <div>
          <label for="password">Password:</label>
          <input type="password" id="password" bind:value={newAccount.password} required>
        </div>
        <div>
          <label for="role">Role:</label>
          <select id="role" bind:value={newAccount.role}>
            <option value="Analyst">Analyst</option>
            <option value="Admin">Admin</option>
          </select>
        </div>
        <button type="submit">Create Account</button>
      </form>
    </section>

    <section>
      <h2>Add New Log Source</h2>
      <form on:submit={addLogSource}>
        <div>
          <label for="sourceName">Source Name:</label>
          <input type="text" id="sourceName" bind:value={newLogSource.name} required>
        </div>
        <div>
          <label for="sourceType">Source Type:</label>
          <select id="sourceType" bind:value={newLogSource.type}>
            <option value="syslog">Syslog</option>
            <option value="winlog">Windows Event Log</option>
            <option value="apache">Apache Log</option>
          </select>
        </div>
        <div>
          <label for="sourceAddress">Source Address:</label>
          <input type="text" id="sourceAddress" bind:value={newLogSource.address} required>
        </div>
        <button type="submit">Add Log Source</button>
      </form>
    </section>

    <section>
      <h2>Add New Host</h2>
      <form on:submit={addHost}>
        <div>
          <label for="hostName">Host Name:</label>
          <input type="text" id="hostName" bind:value={newHost.name} required>
        </div>
        <div>
          <label for="hostIP">IP Address:</label>
          <input type="text" id="hostIP" bind:value={newHost.ip} required>
        </div>
        <button type="submit">Add Host</button>
      </form>
    </section>

    <nav>
      <a href="/">Back to Dashboard</a>
    </nav>
  </div>
</main>

// frontend/src/pages/Settings.jsx
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { getAuthenticationStatus, checkAuth, user } from '../services/authService';
import { getCsrfToken } from '../services/csrfService';
import Navbar from '../components/Navbar';
import '../styles/Settings.css';

const Settings = () => {
    const [error, setError] = useState('');
    const [success, setSuccess] = useState('');
    const [hosts, setHosts] = useState([]);
    const [isLoading, setIsLoading] = useState(false);
    const navigate = useNavigate();
    const formId = 'settings-form';

    useEffect(() => {
        const initSettings = async () => {
            await checkAuth();
            if (!getAuthenticationStatus()) {
                navigate('/login');
                return;
            }
            await populateHostList();
        };

        initSettings();
    }, [navigate]);

    const showAlert = (message, type = 'error') => {
        if (type === 'error') setError(message);
        else setSuccess(message);

        setTimeout(() => {
            setError('');
            setSuccess('');
        }, 5000);
    };

    const populateHostList = async () => {
        try {
            const response = await fetch(`http://localhost:4200/backend/host/all/${user}`, {
                method: 'GET',
                headers: {
                    'X-Form-ID': formId
                },
                credentials: 'include'
            });

            if (response.ok) {
                const hostsData = await response.json();
                setHosts(hostsData);
            } else {
                showAlert('Failed to fetch hosts', 'error');
            }
        } catch (err) {
            console.error('Error fetching hosts:', err);
            showAlert('Error fetching hosts', 'error');
        }
    };

    const handleCopyId = async (id) => {
        try {
            await navigator.clipboard.writeText(id);
            showAlert('ID copied to clipboard!', 'success');
        } catch (err) {
            showAlert('Failed to copy', 'error');
        }
    };

    const handleFileUpload = async (e) => {
        const file = e.target.files[0];
        const hostId = document.getElementById('hostSelect').value;

        if (!file || !hostId) {
            showAlert('Please select a file and a host', 'error');
            return;
        }

        setIsLoading(true);
        const formData = new FormData();
        formData.append('file', file);
        formData.append('host_id', hostId);
        formData.append('account_id', user);

        try {
            const response = await fetch('http://localhost:4200/backend/log/import', {
                method: 'POST',
                headers: {
                    'X-Form-ID': formId
                },
                body: formData,
                credentials: 'include'
            });

            if (response.ok) {
                showAlert('Logs uploaded successfully!', 'success');
                e.target.value = '';
            } else {
                const error = await response.json();
                showAlert(error.message, 'error');
            }
        } catch (err) {
            showAlert('An error occurred while uploading logs', 'error');
        } finally {
            setIsLoading(false);
        }
    };

    const handleNewHost = async (e) => {
        e.preventDefault();
        const hostname = e.target.hostname.value;
        const ipAddress = e.target.ipAddress.value;

        if (!hostname || !ipAddress) {
            showAlert('Please fill in all fields', 'error');
            return;
        }

        try {
            const response = await fetch('http://localhost:4200/backend/host/', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-Form-ID': formId
                },
                body: JSON.stringify({
                    account_id: user,
                    hostname: hostname,
                    ip_address: ipAddress
                }),
                credentials: 'include'
            });

            if (response.ok) {
                showAlert('Host added successfully!', 'success');
                e.target.reset();
                await populateHostList();
            } else {
                const error = await response.json();
                showAlert(error.message, 'error');
            }
        } catch (err) {
            showAlert('An error occurred while adding the host', 'error');
        }
    };

    const handleRuleUpload = async (e) => {
        const file = e.target.files[0];

        if (!file) {
            showAlert('Please select a file', 'error');
            return;
        }

        setIsLoading(true);
        const formData = new FormData();
        formData.append('file', file);
        formData.append('account_id', user);

        try {
            const response = await fetch('http://localhost:4200/backend/rule/import', {
                method: 'POST',
                headers: {
                    'X-Form-ID': formId
                },
                body: formData,
                credentials: 'include'
            });

            if (response.ok) {
                showAlert('Rules uploaded successfully!', 'success');
                e.target.value = '';
            } else {
                const error = await response.json();
                showAlert(error.message, 'error');
            }
        } catch (err) {
            showAlert('An error occurred while uploading rules', 'error');
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="container">
            <h1>SIEM Settings</h1>
            <Navbar />
            
            {error && <div className="alert error">{error}</div>}
            {success && <div className="alert success">{success}</div>}

            <main>
                <section className="agent-info">
                    <div className="info-group">
                        <h3>Account ID</h3>
                        <div className="copy-container">
                            <span>{user}</span>
                            <button 
                                className="copy-btn" 
                                onClick={() => handleCopyId(user)}
                            >
                                Copy
                            </button>
                        </div>
                    </div>

                    <div className="info-group">
                        <h3>Available Hosts</h3>
                        <table id="hostsTable">
                            <thead>
                                <tr>
                                    <th>Host Name</th>
                                    <th>Host ID</th>
                                    <th>IP Address</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {hosts.length === 0 ? (
                                    <tr><td colSpan="4">No hosts available</td></tr>
                                ) : (
                                    hosts.map(host => (
                                        <tr key={host.id}>
                                            <td>{host.hostname}</td>
                                            <td>{host.id}</td>
                                            <td>{host.ip_address}</td>
                                            <td>
                                                <button 
                                                    className="copy-btn"
                                                    onClick={() => handleCopyId(host.id)}
                                                >
                                                    Copy ID
                                                </button>
                                            </td>
                                        </tr>
                                    ))
                                )}
                            </tbody>
                        </table>
                    </div>
                </section>

                <section>
                    <h2>Upload Logs</h2>
                    <div id="input-spinner-container">
                        <select id="hostSelect">
                            <option value="">Select Host</option>
                            {hosts.map(host => (
                                <option key={host.id} value={host.id}>
                                    {host.hostname}
                                </option>
                            ))}
                        </select>
                        <input 
                            type="file" 
                            onChange={handleFileUpload}
                            accept=".log,.txt"
                        />
                        {isLoading && <div className="spinner"></div>}
                    </div>
                </section>

                <section>
                    <h2>Add New Host</h2>
                    <form onSubmit={handleNewHost}>
                        <div className="form-group">
                            <input
                                type="text"
                                id="hostname"
                                name="hostname"
                                placeholder="Hostname"
                                required
                            />
                        </div>
                        <div className="form-group">
                            <input
                                type="text"
                                id="ipAddress"
                                name="ipAddress"
                                placeholder="IP Address"
                                required
                            />
                        </div>
                        <button type="submit">Add Host</button>
                    </form>
                </section>

                <section>
                    <h2>Add New Rule</h2>
                    <div id="input-spinner-container">
                        <input 
                            type="file" 
                            onChange={handleRuleUpload}
                            accept=".yaml,.yml"
                        />
                        {isLoading && <div className="spinner"></div>}
                    </div>
                </section>

            </main>
        </div>
    );
};

export default Settings;
